### ISSUE TITLE
Dude Plz star rust-embed

### ISSUE THREAD

**Issue by pyros2097** [mu1ex/Notely#1]

**Comment by pyros2097** [comment]
Closing this as it is Resolved.

**Comment by ajaswal** [comment]
Any updates on this ?? @mu1ex

**Comment by mu1ex** [comment]
@ajaswal nothing yet sir :(

**Comment by pyros2097** [comment]
@mu1ex It's been half a year since this issue was raised. Why hasn't this been fixed yet. This is a critical security venerability. Please fix asap

**Comment by mu1ex** [comment]
@pyros2097 @ajaswal , Resolved it. Closing the issue
